apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HarrisonZz/DevOps_Deploy.git
    targetRevision: main
    path: kubernetes/argocd/applications/monitor   # ğŸ‘ˆ å­ Application YAML æ‰€åœ¨ç›®éŒ„
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd                      # å­ Application æœƒå»ºåœ¨ argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - WaitForChildren=true
      - RespectResourceOrder=true
